- Dockerfile
If we don't specify a host, then uvicorn defaults to localhost, which means it won't be accessible outside of the container.
We need to specify the host explicitly as 0.0.0.0 to allow access outside of localhost
> Add host and port specification to dockerfile

- pyproject.toml
- src/ai4gd_momconnect_haystack/api.py
- tests/test_api.py
- uv.lock
Add a prometheus metrics endpoint that is instrumented for FastAPI, so that we can get metrics on our API
> Add prometheus metrics endpoint

- .gitignore
- src/ai4gd_momconnect_haystack/doc_store.py
- src/ai4gd_momconnect_haystack/evaluation/data/evaluation_results_20250616.txt
- src/ai4gd_momconnect_haystack/evaluation/data/ground_truth.json
- src/ai4gd_momconnect_haystack/evaluation/data/llm_run_results.json
- src/ai4gd_momconnect_haystack/evaluation/evaluator.py
- src/ai4gd_momconnect_haystack/main.py
- src/ai4gd_momconnect_haystack/models.py
- src/ai4gd_momconnect_haystack/static_content/dma.json
- src/ai4gd_momconnect_haystack/static_content/kab.json
- src/ai4gd_momconnect_haystack/tasks.py
- src/ai4gd_momconnect_haystack/utilities.py
- tests/test_tasks.py
**PR Summary: Add Batch Scoring and Reporting to Simulation Runner**
**What this PR does**
This PR introduces a robust and scalable batch scoring feature that processes simulation outputs. After a simulation completes, this new logic calculates detailed scores for all applicable assessments and augments the original output with a full scoring report, including total scores, percentages, and min/max ranges.
**Key Changes**
- **New Scoring Functions (`tasks.py`):**
- `score_assessment_from_simulation`: The main orchestration function that takes a simulation output and an assessment_id to produce a final score report.
- `_score_and_format_turn`: A helper function that processes a single conversational turn, adding score and error data directly to it.
- `_calculate_assessment_score_range`: A …
> Assessment score mapping

- src/ai4gd_momconnect_haystack/tasks.py
- tests/test_tasks.py
Currently there's an assumption that the user context dictionary has an "other" field, and the value of that field is a dictionary.
Since in the API we default to an empty dictionary with no "other" fields, it's best if we don't make that assumption, and instead add the "other" field only when we need to add something to it.
> Handle empty context for other context fields

- src/ai4gd_momconnect_haystack/api.py
- src/ai4gd_momconnect_haystack/main.py
- src/ai4gd_momconnect_haystack/pipelines.py
- src/ai4gd_momconnect_haystack/tasks.py
- tests/test_api.py
- tests/test_tasks.py
Currently the assessment doesn't go from one question to another properly. The code is also a bit difficult to understand what is going on.
In order to address this, I did a few things:
- Only the validate response function should advance the question number, since only if the response is valid should we advance to the next question, so the contextualise question function no longer returns the question number, since it shouldn't update it
- I've renamed some of the function arguments and return values, to make it clearer what they are referring to
- I've added in the doc strings where we're using 1-based indexing.
> Fix assessment ordering issue

- pyproject.toml
- uv.lock
Currently, the application fails to startup if you try to use postgresql in the build docker image, complaining that ther's no pq wrapper available (psycopg_c or psycopg_binary).
This PR updates the dependancy to include the optional binary dependancies, so that the binary is also installed (the other option here was to apt install it, but this seemed cleaner as an option)
> Add binary build for psycopg

- README.md
- src/ai4gd_momconnect_haystack/api.py
- src/ai4gd_momconnect_haystack/doc_store.py
- src/ai4gd_momconnect_haystack/enums.py
- src/ai4gd_momconnect_haystack/main.py
- src/ai4gd_momconnect_haystack/pipelines.py
- src/ai4gd_momconnect_haystack/pydantic_models.py
- src/ai4gd_momconnect_haystack/sqlalchemy_models.py
- src/ai4gd_momconnect_haystack/static_content/assessment_ends.json
- src/ai4gd_momconnect_haystack/tasks.py
- src/ai4gd_momconnect_haystack/utilities.py
- tests/test_api.py
- tests/test_tasks.py
- `README.md`
- Added information about the new `/assessment-end` endpoint that handles end-of-pre-assessment messaging
- `api.py`
- Added assessment scoring to the `/assessment` endpoint
- Added the `/assessment-end` endpoint
- Refactored the loading of content files from JSON to load the data into new Pydantic models
- Developed custom ingestion functions for the different types of content and updated `setup_document_store()` to use these function accordingly
- `enums.py`
- Created this new file to host our `Enum` classes to avoid circular imports that started appearing with the new code changes
- `main.py`
- Cleaned up some old/unnecessary comments
- Revamped the simulation to also perform the end-of-pre-assessment messaging journeys
- Changed the order of the simulation's KAB …
> Implementing assessment scoring, skip thresholds and end-of-assessment messaging

- src/ai4gd_momconnect_haystack/api.py
- src/ai4gd_momconnect_haystack/assessment_logic.py
- src/ai4gd_momconnect_haystack/crud.py
- src/ai4gd_momconnect_haystack/evaluation/data/simulation_run_results_250630-1930.json
- src/ai4gd_momconnect_haystack/evaluation/data/simulation_run_results_250630-1930.report.txt
- src/ai4gd_momconnect_haystack/evaluation/data/simulation_run_results_250630-1933.json
- src/ai4gd_momconnect_haystack/evaluation/data/simulation_run_results_250630-1933.report.txt
- src/ai4gd_momconnect_haystack/evaluation/data/simulation_run_results_250630-1935.json
- src/ai4gd_momconnect_haystack/evaluation/data/simulation_run_results_250630-1935.report.txt
- src/ai4gd_momconnect_haystack/evaluation/data/simulation_run_results_250630-1938.json
- src/ai4gd_momconnect_haystack/evaluation/data/simulation_run_results_250630-1938.report.txt
- src/ai4gd_momconnect_haystack/evaluation/data/simulation_run_results_250701-0316.json
- src/ai4gd_momconnect_haystack/evaluation/data/simulation_run_results_250701-0316.report.txt
- src/ai4gd_momconnect_haystack/evaluation/data/simulation_run_results_250701-0319.json
- src/ai4gd_momconnect_haystack/evaluation/data/simulation_run_results_250701-0319.report.txt
- src/ai4gd_momconnect_haystack/evaluation/data/simulation_run_results_250701-0322.json
- src/ai4gd_momconnect_haystack/evaluation/data/simulation_run_results_250701-0322.report.txt
- src/ai4gd_momconnect_haystack/evaluation/data/simulation_run_results_250701-0324.json
- src/ai4gd_momconnect_haystack/evaluation/data/simulation_run_results_250701-0324.report.txt
- src/ai4gd_momconnect_haystack/main.py
- src/ai4gd_momconnect_haystack/pipelines.py
- src/ai4gd_momconnect_haystack/static_content/anc_survey.json
- src/ai4gd_momconnect_haystack/static_content/assessment_ends.json
- src/ai4gd_momconnect_haystack/static_content/kab.json
- src/ai4gd_momconnect_haystack/tasks.py
- src/ai4gd_momconnect_haystack/utilities.py
- tests/test_api.py
- tests/test_tasks.py
_These changes are aimed to improve user friendliness. While I would have loved to code some of these changes in a more structured/granularized/parsimonious way, such optimizations can wait for post-user-testing._
`static_content/`
- Modified some source content pieces to NOT contain their expected responses anymore. The expected responses are now, in a more hardcoded fashion, being formatted and inserted differently into 1) contextualized questions, and 2) system prompts for response validation/data extraction. This is to enforce a more user friendly journey and to enhance data extraction.
`api.py`
- The service persona being added to the first system prompt in a `ChatHistory` erroneously used a whole dictionary instead of just the value in the "persona" key. This has been fixed.
- Added …
> Pipeline improvements wrt user friendliness

- src/ai4gd_momconnect_haystack/main.py
- src/ai4gd_momconnect_haystack/pipeline_prompts.py
The `run_clinic_visit_data_extraction_pipeline` was failing when processing user responses that included the lettered prefix of an option (e.g., a., b.). As shown in the "before" logs, when a user responded with the full option text including its prefix (e.g., "a. Very easy"), the model would return the entire string. This caused the `JsonSchemaValidator` to fail because it expected only the option's text ("Very easy") to match the enum of valid responses. This led to unnecessary retries and a poor user experience.
This PR resolves the issue by making the `CLINIC_VISIT_DATA_EXTRACTION_PROMPT` more explicit.
- **Added a New Rule:** A new rule (Rule 3) was added to instruct the LLM to strip any lettered or numbered prefixes from its final `validated_response`.
- **Added a New Example:** …
> updated CLINIC_VISIT_DATA_EXTRACTION_PROMPT

- src/ai4gd_momconnect_haystack/api.py
- src/ai4gd_momconnect_haystack/pydantic_models.py
- tests/test_api.py
Returns the processed_answer back to the journey to save.
We have the question number and assessment name in the journey so we'll save something like:
behaviour-pre-assessment-1: very confident
> Return processed_answer on assessments to save

- src/ai4gd_momconnect_haystack/evaluation/data/simulation_results_onboarding.json
- src/ai4gd_momconnect_haystack/evaluation/data/simulation_results_onboarding.report.txt
- src/ai4gd_momconnect_haystack/pipeline_prompts.py
- src/ai4gd_momconnect_haystack/pipelines.py
This PR addresses inaccuracies in the AI's intent detection capabilities that were identified across all simulation reports ( onboarding, dma, kab, anc-survey). The previous model had a strong bias towards classifying any user input as a direct answer (`JOURNEY_RESPONSE`), failing to correctly identify when a user was asking a question, making small talk, or reporting an issue.
Key Changes and Rationale
1. **Advanced Intent Prompting**
- Why: The primary reason for the inaccuracies was that the INTENT_DETECTION_PROMPT was too simple. It didn't provide enough guidance for the LLM to distinguish between nuanced user inputs across different survey contexts.
- What we did: We implemented a more sophisticated "Chain of Thought" prompt. This new prompt requires the LLM to first write out its …
> Intent detection pipeline Refactor

- src/ai4gd_momconnect_haystack/api.py
- src/ai4gd_momconnect_haystack/tasks.py
- tests/test_api.py
- tests/test_tasks.py
This PR addresses two critical bugs in the onboarding flow that were identified during end-to-end simulation and testing:
1. Repair on Consent: Users who provided a valid consent (e.g., "yes") to the introductory message were incorrectly shown a "conversation repair" prompt.
2.  No Transition to DMA: The flow would end after the new summary screen instead of signaling the start of the DMA assessment.
The changes in this PR resolve these issues by correcting the logical flow in the API and tasks, making the onboarding experience more robust and ensuring the user journey continues as expected.
**Key Changes**
- **Corrected Consent Handling** (api.py): The onboarding endpoint has been updated to cleanly separate the handling of the initial consent response from the first question-and-answer …
> Summary Screen Bugfix

- src/ai4gd_momconnect_haystack/api.py
- src/ai4gd_momconnect_haystack/pipeline_prompts.py
- src/ai4gd_momconnect_haystack/pipelines.py
- src/ai4gd_momconnect_haystack/static_content/anc_survey.json
- src/ai4gd_momconnect_haystack/tasks.py
- src/ai4gd_momconnect_haystack/utilities.py
- tests/test_api.py
- tests/test_tasks.py
**Fix: Resolve ANC Survey Bugs and Implement Re-engagement**
This PR addresses several critical bugs in the ANC Survey reported by QA. The primary issue was the survey's brittle conversational flow, which relied on exact-string matching and had incomplete logic paths, leading to unpredictable behaviour and premature termination of the survey.
Additionally, this PR completes the backend implementation for the re-engagement feature, aligning it with the Figma design specifications.
Key changes made:
- Refactored ANC Survey Logic: The entire survey flow was refactored to use a robust, key-based system instead of fragile text matching. This involved updating the AI prompt (`pipeline_prompts.py`), the data extraction task (`tasks.py`), and the core flow logic (`pipelines.py`).
- Completed …
> Anc suvery bug fix

- src/ai4gd_momconnect_haystack/tasks.py
- tests/test_api.py
**Description**
This PR fixes a critical bug where the application would crash with a ValueError if a user was re-engaged for a second time after dropping out of an assessment flow.
**Root Cause:**
If a user received a "Ready to continue?" prompt and then went silent again, their state was saved with a step identifier of "awaiting_reminder_response". On the next re-engagement, the logic that builds the AssessmentResponse tried to convert this string to an integer, causing a fatal crash.
**Solution:**
The `handle_journey_resumption_prompt` helper function in `tasks.py` has been updated to be more robust. It now checks if the `current_step_identifier` is a digit before attempting to convert it to an integer. If it's not a digit (e.g., "awaiting_reminder_response"), it safely defaults to …
> Bugfix(tasks): Prevent crash on re-engagement from reminder prompt

- src/ai4gd_momconnect_haystack/tasks.py
This PR expands the yes/no intent classifier to recognise common and South African variations like "yup" and "nee". This fixes a bug where users' responses were misunderstood, improving the conversational robustness.
> Expanded affirmative mapping on YesOrNo questions

- src/ai4gd_momconnect_haystack/api.py
- src/ai4gd_momconnect_haystack/crud.py
- tests/test_api.py
- tests/test_crud.py
Fix import order on api.py and crud.py
On ANC surveys it deletes chat history for new sessions where user_input is "" + a test for this
Adds tests for the `delete_chat_history_for_user` function in crud.py
> Delete chat history for new anc survey + some tests

- docker-compose.yaml
- src/ai4gd_momconnect_haystack/api.py
- src/ai4gd_momconnect_haystack/main.py
- src/ai4gd_momconnect_haystack/tasks.py
- tests/test_api.py
**Context**
The onboarding endpoint was failing to handle conversational repair correctly. Specifically, when users provided ambiguous or letter-based responses (e.g., "Portland" or "f"), the system repeatedly triggered repair messages instead of progressing to the next step. This caused conversational loops and broke the onboarding experience.
**What Changed:**
- Standardised return contract:
- process_onboarding_step now consistently returns (updated_context, next_question, processed_input) instead of just (context, question).
- Ensures the system has both the raw input and the normalised/processed interpretation.
- Explicit state machine flow in /v1/onboarding:
- Clear handling for JOURNEY_RESPONSE, SKIP_QUESTION, REPAIR, REQUEST_TO_BE_REMINDED, and CHITCHAT.
- Prevents ambiguity …
> Refactor Onboarding Flow for Conversational Repair

- Dockerfile
- log_conf.yaml
- src/ai4gd_momconnect_haystack/api.py
- src/ai4gd_momconnect_haystack/migrations/env.py
This PR does two things to fix the logging issue:
1. Removes the logging config overrride from alembic. Turns out this was a file in our repo that we control, so once I found that it was easy enough to remove
2. Move the logging config to uvicorn for the API. If we do this in our app, uvicorn starts up first and applies its logging, and then we're trying to override things. Much easier to just pass a logging config to uvicorn from the beginning, and have it apply to everything. This means that we supply the logging config as a file, and pass the file path to the uvicorn command
> Fix migration messing with logging config

- src/ai4gd_momconnect_haystack/tasks.py
- tests/test_tasks.py
This pull request improves the handling and testing of reminder scheduling for KAB (Knowledge, Attitude, Behaviour) flows. The main focus is on treating these flows consistently and ensuring the correct acknowledgement messages and trigger times are used. Key changes include updating the logic for identifying KAB flows and adding comprehensive tests for their reminder behavior.
**Reminder scheduling logic improvements:**
- Updated the `handle_reminder_request` function to treat "knowledge" and "attitude" flows the same as "behaviour" by mapping them all to the `kab` schedule key.
**Testing enhancements:**
- Added a new parameterized test, `test_handle_reminder_request_kab_acknowledgements`, to verify that KAB flows use the correct acknowledgement message and trigger time based on the …
> Enhance KAB flow handling in reminder requests and add tests

- src/ai4gd_momconnect_haystack/api.py
- src/ai4gd_momconnect_haystack/assessment_logic.py
- tests/test_tasks.py
**Description**
This PR resolves a bug where the assessment-end flow would incorrectly reject valid user inputs like "ok" for the ease-of-completion question, forcing a repair loop.
The root cause was that the validate_assessment_end_response function relied solely on a case-sensitive AI pipeline that failed to match lowercase inputs like "ok" to the expected uppercase option "OK" from the flow's configuration.
The fix introduces rule-based logic to the `validate_assessment_end_response` function. It now reliably handles case variations (e.g., "ok", "Ok") and single-letter inputs (e.g., "c") before falling back to the AI pipeline, ensuring common responses are always accepted. The new test `test_validate_ease_of_completion_handles_ok_variations` was added to confirm this fix now works as …
> PR Title: fix(assessment): Improve validation for ease-of-completion question
